- name: Install pip
  apt:
    name: python-pip
    state: present
- name: Install python docker adapter
  pip:
    name: docker
    state: present
- name: Install docker-compose
  pip:
    name: docker-compose
    state: present
- name: Install docker dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
- name: Add docker apt-key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add docker apt-repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
- name: Install docker-ce
  apt:
    name: docker-ce
    state: present

