- name: Copy docker-compose.yml file
  copy:
    src: docker-compose.yml
    dest: /tmp

- name: Run containers described in docker-compose file
  docker_service:
    project_src: /tmp
    state: present
