apiVersion: v1
kind: ReplicationController
metadata:
  name: djch-rc-test
spec:
  replicas: 5
  selector:
    stage: main-lb-pod-test
  template:
    metadata:
      labels:
        stage: main-lb-pod-test
    spec:
      containers:
        - name: mainlb-container
          image: eugenebad/k8s-tut-mainlb
          ports:
            - containerPort: 80