apiVersion: v1
kind: Service
metadata:
  name: djch-backend-svc
spec:
  type: NodePort
  ports:
    - name: api-port
      port: 30003
      targetPort: 8000
      protocol: TCP
  selector:
    app: djch-backend-pod