apiVersion: v1
kind: Service
metadata:
  name: djch-mainlb-svc
spec:
  type: NodePort
  ports:
    - name: main-app-entry-port
      nodePort: 30001
      port: 80
      protocol: TCP
    - name: api-entry-port
      nodePort: 30002
      port: 8000
      protocol: TCP
  selector:
    app: djch-mainlb-pod