apiVersion: v1
kind: Service
metadata:
  name: djch-mainlb-svc
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 80
      protocol: TCP
    - port: 8000
      nodePort: 30001
      protocol: TCP
  selector:
    app: djch-mainlb-pod