apiVersion: v1
kind: Service
metadata:
  name: djch-mainlb-svc
spec:
  type: NodePort
  ports:
    - name: main-app-entry-port
      nodePort: 30001 #Externally, the service is accessed on this port
      port: 80 # Internally/clusterwide, the service is accessed on this port; unless explicitly specified, targetPort also takes up this value
      protocol: TCP
    - name: api-entry-port
      nodePort: 30002
      port: 8000
      protocol: TCP
  selector:
    app: djch-mainlb-pod
  sessionAffinity: ClientIP