version: "3"
services:
  nginx:
    image: eugenebad/djchangular_nginx
    ports:
      - "80:80"
      - "8000:8000"
    networks:
      - wsproxy

  django:
    image: eugenebad/djchangular_django
    networks:
      - wsproxy

networks:
  wsproxy:
    driver: bridge

